# Copyright (C) 2022 - : Kristofer Tingdahl
# Licensed under the Mozilla public license 2.0

name: tingdahl-observatory-cli
base: core20 # the base snap is the execution environment for this snap
summary: Score your site's HTTPS practices
version: git
description: |
  Mozilla Observatory scans websites for security issues. This is the cli
  version of observability that allows CI/CD tooling to test websites
  as a part of the build and release process.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

parts:
  observatory:
    plugin: npm
    npm-node-version: 16.18.0
    source: https://github.com/tingdahl/observatory-cli-snap.git

apps:
  observatory:
    command: bin/observatory
    plugs:
      - network

